<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="tbNewEnumeration" type="button" title="Add a new Enumeration" img="newproblem.png" imgdis="newproblem.png">
		<![CDATA[<div style="margin-top:-5px;">New</div> ]]>
	</item>
	<item id="delete" type="button" title="Delete Enumeration" img="removeproblem.png" imgdis="removeproblem.png">
		<![CDATA[<div style="margin-top:-5px;">Delete</div> ]]>
	</item>
	<item id="refresh" type="button" title="Refresh Enumeration" img="refresh.png" imgdis="refresh.png">
		<![CDATA[<div style="margin-top:-5px;">Refresh</div> ]]>
	</item>
	<item id="tbNewObject" type="button" title="Add a new Object" img="newproblem.png" imgdis="newproblem.png" enabled="false">
		<![CDATA[<div style="margin-top:-5px;">New Object</div> ]]>
	</item>
	<item id="tbEditObject" type="button" title="Edit Object" img="editproblem.png"  imgdis="editproblem.png" enabled="false">
		<![CDATA[<div style="margin-top:-5px;">Edit Object</div>]]>
	</item>
</toolbar>
