<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="add" type="button" title="<?=__('New')?>" img="newproblem.png" imgdis="newproblem.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('New')?></div> ]]>
	</item>
	<item id="edit" type="button" title="<?=__('Edit')?>" img="editproblem.png" imgdis="editproblem.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Edit')?></div> ]]>
	</item>
	<item id="delete" type="button" title="<?=__('Delete')?>" img="removeproblem.png"  imgdis="removeproblem.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Delete')?></div>]]>
	</item>
	<item id="refresh" type="button" title="<?=__('Refresh')?>" img="refresh.png"  imgdis="refresh.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Refresh')?></div>]]>
	</item>
</toolbar>
