<?='<?xml version="1.0"?>'?>
<menu id="0">
<?if($this->type == 'eob'):?>
	<item id="processBatch" text="<?=__('Process Batch')?>" img="" />
<?else:?>
	<item id="selectAll" text="<?=__('Select All')?>" img="" />
	<item id="addToQueue" text="<?=__('Add to queue')?>" img="" />
	<item id="batchOpen" text="<?=__('Batch Open')?>" img="" />
	<item id="batchClose" text="<?=__('Batch Close')?>" img="" />
	<item id="patientDetails" text="<?=__('Patient Details')?>" img="" />
	<item id="checkRules" text="<?=__('Check Rules')?>" img="" />
	<item id="claimInquiry" text="<?=__('Claim Inquiry')?>" img="" />
<?endif;?>
</menu>
