<?=$this->xmlHeader?>
<toolbar>
<item id="sep0" type="separator"/>
<item id="newnote" type="button" img="newproblem.png" height="45"><![CDATA[ <div style="margin-top:-5px;"><?=__("New Note")?></div> ]]></item>
<item id="editproblem" type="button" img="editproblem.png" height="45" disabled="disabled"><![CDATA[ <div style="margin-top:-5px;"><?=__("Edit Note")?></div> ]]></item>
<item id="deletenote" type="button" img="removeproblem.png" height="45" disabled="disabled"><![CDATA[ <div style="margin-top:-5px;"><?=__("Delete Note")?></div> ]]></item>
<item id="refresh" type="button" img="refresh.png" height="45"><![CDATA[ <div style="margin-top:-5px;"><?=__('Refresh')?></div> ]]></item>
</toolbar>
