<?='<?xml version="1.0" ?>'?>
<menu id="0">
	<item text="<?=__('Enter New Allergy')?>" img="" id="newAllergy" />
	<item text="<?=__('Mark Selected Allergy as Entered in Error')?>" img="" id="enteredInError" />
	<item text='<?=__('Mark patient as having "No Known Allergies" (NKA)')?>' img="" id="nka" />
	<item text="<?=__('Mark allergy Active')?>" img="" id="markActive" />
	<item text="<?=__('Mark allergy Inactive')?>" img="" id="markInactive" />
	<item text="<?=__('Showing')?>" img="" id="showing">
		<item text="<?=__('Active Allergies')?>" type="checkbox" id="showing_active"  checked="true" />
		<item text="<?=__('Inactive Allergies')?>" type="checkbox" id="showing_inactive" checked="true" />
	</item>
</menu>
