<div style="width:100%;height:auto;">
                <strong>Patient Information</strong>
                <div style="float:left;">
                        <div>
                        <div style="display:table-cell; vertical-align:middle; height:100px;">
                                <img src="../img/no-person-image.png">
                        </div>
                        </div>
                </div>
                <div style="float:left;">
                        <div style="margin-left:10px;">
                        <strong>Simpson, Bart</strong><br />
                        MRN: 94882<br />
                        Age/Sex: 28 (Male)<br />
                        DOB: 11/11/1980<br />
                        Location: HealthStar - Waiting Room<br />
                        </div>
                </div>
        </div>
