<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="sep0" type="separator"/>
	<item id="new_distinct_id" type="button" img="newproblem.png" height="45"><![CDATA[<div style="margin-top:-5px;"><?=__('New Distinct Section')?></div>]]></item>
	<item id="copy_template" type="button" img="copydocument.png" imgdis="copydocument.png" height="45" enabled="false"><![CDATA[<div style="margin-top:-5px;"><?=__('Copy Template')?></div>]]></item>
	<item id="holidays" type="button" img="dhtmlxgrid_icon.gif" imgdis="dhtmlxcalendar_icon.gif" height="45"><![CDATA[<div style="margin-top:-5px;"><?=__('Holidays')?></div>]]></item>
</toolbar>
