<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="tbStart" type="button" title="<?=__('Start Service')?>" img="start.png" imgdis="start.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Start')?></div> ]]>
	</item>
	<item id="tbStop" type="button" title="<?=__('Stop Service')?>" img="stop.png" imgdis="stop.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Stop')?></div> ]]>
	</item>
	<item id="tbRestart" type="button" title="<?=__('Restart Service')?>" img="reload.png" imgdis="reload.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Restart')?></div>]]>
	</item>
	<!--<item id="tbClear" type="button" title="<?=__('Clear Cache')?>" img="clear.png" imgdis="clear.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Clear')?></div>]]>
	</item>
	<item id="tbEnable" type="button" title="<?=__('Enable Cache')?>" img="editproblem.png" imgdis="editproblem.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Enable')?></div>]]>
	</item>
	<item id="tbDisable" type="button" title="<?=__('Disable Cache')?>" img="removeproblem.png" imgdis="removeproblem.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Disable')?></div>]]>
	</item>-->
	<item id="tbMenuReload" type="button" title="<?=__('Reload')?>" img="refresh.png" imgdis="refresh.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Reload')?></div>]]>
	</item>
	<item id="tbPermissionStart" type="button" title="<?=__('Start Service')?>" img="start.png" imgdis="start.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Start')?></div> ]]>
	</item>
	<item id="tbPermissionStop" type="button" title="<?=__('Stop Service')?>" img="stop.png" imgdis="stop.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Stop')?></div> ]]>
	</item>
	<item id="tbPermissionReload" type="button" title="<?=__('Reload Service')?>" img="reload.png" imgdis="reload.png">
		<![CDATA[<div style="margin-top:-5px;"><?=__('Reload')?></div>]]>
	</item>
</toolbar>
