<?='<?xml version="1.0" encoding="UTF-8" ?>'; ?>
<?=$this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?=$this->headTitle() ?>
<?//=$this->headLink() ?>
<?//=$this->headScript() ?>

<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl?>/css/global.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl?>/css/style.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl?>/css/dhtmlxwindows.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl?>/css/dhtmlxwindows_clear_silver.css" />
<script type="text/javascript" src="<?=$this->baseUrl?>/js/dhtmlxcommon.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl?>/js/dhtmlxwindows.js"></script>

</head>
<body>
<?=$this->layout()->content?>
</body>
</html>
