<?=$this->xmlHeader?>
<toolbar>
	<item id="sep0" type="separator"/>
	<item id="check" type="button" img="reload.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Check')?></div>]]></item>
	<item id="details" type="button" img="details.png" imgdis="details.png" height="45" enabled="false"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Details')?></div>]]></item>
	<item id="delete" type="button" img="removeproblem.png" imgdis="removeproblem.png" height="45" enabled="false"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Delete')?></div>]]></item>
	<item id="apply" type="button" img="save.png" imgdis="save.png" height="45" enabled="false"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Apply')?></div>]]></item>
	<item id="refresh" type="button" img="refresh.png" imgdis="refresh.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Refresh')?></div>]]></item>
	<item id="sep1" type="separator"/>
	<item id="sep2" type="separator"/>
	<item id="sep3" type="separator"/>
	<item id="sep4" type="separator"/>
	<item id="upload" type="button" img="save.png" imgdis="save.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Upload')?></div>]]></item>
</toolbar>
