<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="tbNewFormulary" type="button" title="Add a new Formulary" img="newproblem.png" imgdis="newproblem.png">
		<![CDATA[<div style="margin-top:-5px;">New</div> ]]>
	</item>
	<item id="tbDisableFormulary" type="button" title="Disable Formulary" img="editproblem.png"  imgdis="editproblem.png" enabled="false">
		<![CDATA[<div style="margin-top:-5px;">Disable</div>]]>
	</item>
	<item id="tbEnableFormulary" type="button" title="Enable Formulary" img="editproblem.png"  imgdis="editproblem.png" enabled="false">
		<![CDATA[<div style="margin-top:-5px;">Enable</div>]]>
	</item>
	<item id="tbDefaultFormulary" type="button" title="Set Default Formulary" img="editproblem.png"  imgdis="editproblem.png" enabled="false">
		<![CDATA[<div style="margin-top:-5px;">Set Default</div>]]>
	</item>
	<item id="tbDeleteFormulary" type="button" title="Delete Formulary" img="removeproblem.png" imgdis="removeproblem.png" enabled="false">
		<![CDATA[<div style="margin-top:-5px;">Delete</div> ]]>
	</item>
	<item  id="tbRefreshFormulary" type="button" title="Refresh Formulary List" img="refresh.png" imgdis="refresh.png">
		<![CDATA[<div style="margin-top:-5px;">Refresh</div>]]>
	</item>
</toolbar>
