<<?='?'?>xml version="1.0" encoding="UTF-8"<?="?"?>>
<menu id="0">
	<item text="<?=__('Approved')?>" img="" id="approved" />
	<item text="<?=__('Denied')?>" img="" id="denied" />
	<item text="<?=__('Direct denied')?>" img="" id="directDenied">
		<item text="Patient unknown to the Prescriber" img="" id="directDenied_AA" />
		<item text="Patient never under Prescriber care" img="" id="directDenied_AB" />
		<item text="Prescriber not associated with this practice or location" img="" id="directDenied_AN" />
	</item>
	<item text="<?=__('Mark as resolved')?>" img="" id="markAsResolved" />
	<item id="ms1" type="separator"/>
	<item text="<?=__('View raw message')?>" img="" id="viewRawMessage" />
	<item text="<?=__('View gateway response raw message')?>" img="" id="viewGatewayResponseRawMessage" />
</menu>
