<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="filter" type="button" img="filter.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Filter')?></div>]]></item>
	<!--<item id="patient" type="button" img="filter.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Patient')?></div>]]></item>-->
	<item id="settings" type="button" img="settings.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Settings')?></div>]]></item>
	<item id="checkInbound" type="button" img="getStatus.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Check Inbound')?></div>]]></item>
	<item id="refresh" type="button" img="refresh.png" height="45"><![CDATA[<div style="margin:-2px 0 0 5px;"><?=__('Refresh')?></div>]]></item>
</toolbar>
