<<?="?"?>xml version="1.0" encoding="UTF-8"<?="?"?>>
<<?="?"?>xfa generator="XFA2_4" APIVersion="2.6.7116.0"<?="?"?>>
<xdp:xdp xmlns:xdp="http://ns.adobe.com/xdp/" timeStamp="2008-01-16T02:06:28Z" uuid="6aee0086-4ab9-40a0-8119-5a0f3d39220a">
<xfa:datasets xmlns:xfa="http://www.xfa.org/schema/xfa-data/1.0/">
<xfa:data>
<form1><?=$this->xmlData?></form1>
</xfa:data>
</xfa:datasets>
<pdf  xmlns="http://ns.adobe.com/xdp/pdf/" >
<document>
<chunk><?=$this->pdfBase64?></chunk>
</document>
</pdf>
</xdp:xdp>
