<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
        <item type="button" img="newproblem.png" imgdis="newproblem.png" id="medtbNewMedication" title="Add a new Medication">
<![CDATA[<div style="margin-top:-5px;">New</div> ]]>
</item>
	<item type="button" img="removeproblem.png" imgdis="removeproblem.png" id="delete" title="Delete" enabled="false"><![CDATA[<div style="margin-top:-5px;">Delete</div> ]]></item>
	<item type="button" img="copy.png" imgdis="copy.png" id="copyAndDiscontinue" title="Copy and Discontinue" enabled="false"><![CDATA[<div style="margin-top:-5px;">Copy &amp; Discontinue</div> ]]></item>
<!--<item id="medtbChangeMedication" type="button" title="Change an Existing Medication" img="editproblem.png"  imgdis="editproblem.png" enabled="false">
<![CDATA[<div style="margin-top:-5px;">Change</div>]]>
</item>-->
<item id="medtbCancelMedication" type="button" title="Discontinue / Cancel an Existing Medication" img="removeproblem.png" imgdis="removeproblem.png" enabled="false">
<![CDATA[<div style="margin-top:-5px;">Discontinue</div> ]]>
</item>
<item  id="medtbCopyMedication" type="button" title="Copy" img="copydocument.png" imgdis="copydocument.png" enabled="false">
<![CDATA[<div style="margin-top:-5px;">Copy</div>]]>
</item>
<item  id="medtbDetailsMedication" type="button" title="Details" img="details.png" imgdis="details.png" enabled="false">
<![CDATA[<div style="margin-top:-5px;">Details</div>]]>
</item>
	<item  id="filter" type="button" title="<?=__('Filter')?>" img="filter.png" imgdis="filter.png" >
		<![CDATA[<div style="margin-top:-5px;"><?=__('Filter')?></div>]]>
	</item>
<item  id="medtbRefreshMedication" type="button" title="Refresh" img="refresh.png" imgdis="refresh.png" >
<![CDATA[<div style="margin-top:-5px;">Refresh</div>]]>
</item>
</toolbar>
