<?=$this->xmlHeader?>
<toolbar>
	<item id="reload_permissions" type="button" img="reload.png" height="45"><![CDATA[ <div style="margin-top:-5px;">Reload Permissions</div> ]]></item>
	<item id="saveTemplate" type="button" img="save.png" height="45"><![CDATA[<div style="margin-top:-5px;"><?=__('Save Template')?></div>]]></item>
	<item id="loadTemplate" type="button" img="getStatus.png" height="45"><![CDATA[<div style="margin-top:-5px;"><?=__('Load Template')?></div>]]></item>
</toolbar>
