truncate menu;
INSERT INTO `menu` VALUES (1, 'a', 1, '', 'children', 0, '', '', 'main');
INSERT INTO `menu` VALUES (2, 'default', 1, '', 'children', 10, 'Actions', '', 'main');
INSERT INTO `menu` VALUES (3, 'default', 2, '', 'children', 100, 'Add Appointment', 'javascript:showAddAppointment()', 'RAW');
INSERT INTO `menu` VALUES (4, 'default', 2, '', 'children', 200, 'Search', 'Appointment/Search', 'main');
INSERT INTO `menu` VALUES (5, 'default', 2, '', 'children', 300, 'Filters', 'javascript:showCalendarFilters()', 'RAW');
INSERT INTO `menu` VALUES (6, 'default', 2, '', 'children', 400, 'Day', 'CalendarDisplay/Day', 'main');
INSERT INTO `menu` VALUES (7, 'default', 1, '', 'children', 20, 'Reports', '', 'main/CalendarDisplay');
INSERT INTO `menu` VALUES (8, 'default', 1, '', 'children', 30, 'Admin', '', 'main');
INSERT INTO `menu` VALUES (9, 'default', 8, '', 'children', 100, 'Schedules', 'Schedule/list', 'main');
INSERT INTO `menu` VALUES (10, 'default', 8, '', 'children', 200, 'Templates', 'AppointmentTemplate/list', 'main');
INSERT INTO `menu` VALUES (11, 'patient', 1, '', 'children', 10, 'Actions', '', 'main');
INSERT INTO `menu` VALUES (12, 'patient', 11, '', 'children', 100, 'Add Patient', 'Patient/Add', 'main');
INSERT INTO `menu` VALUES (13, 'patient', 11, '', 'children', 200, 'Search', 'PatientFinder/Find', 'main');
INSERT INTO `menu` VALUES (14, 'patient', 11, '', 'children', 300, 'Dashboard', 'PatientDashboard/View', 'main');
INSERT INTO `menu` VALUES (15, 'patient', 11, '', 'children', 400, 'Add Encounter', 'Encounter/Add', 'main');
INSERT INTO `menu` VALUES (16, 'patient', 11, '', 'children', 500, 'Documents', 'Document/List', 'main');
INSERT INTO `menu` VALUES (17, 'patient', 1, '', 'children', 20, 'Reports', '', 'main/Patient');
INSERT INTO `menu` VALUES (18, 'patient', 1, '', 'children', 30, 'Admin', '', 'main');
INSERT INTO `menu` VALUES (19, 'patient', 18, '', 'children', 100, 'Merge Queue', 'PatientMerge/List', 'main');
INSERT INTO `menu` VALUES (20, 'billing', 1, '', 'children', 10, 'Actions', '', '');
INSERT INTO `menu` VALUES (21, 'billing', 20, '', 'children', 100, 'Claims', 'Claim/List', 'main');
INSERT INTO `menu` VALUES (22, 'billing', 20, '', 'children', 200, 'Master Account History', 'MasterAccountHistory/View', 'main');
INSERT INTO `menu` VALUES (23, 'billing', 1, '', 'children', 20, 'Reports', '', 'main/Billing');
INSERT INTO `menu` VALUES (24, 'billing', 1, '', 'children', 30, 'Admin', '', 'main');
INSERT INTO `menu` VALUES (25, 'billing', 24, '', 'children', 100, 'Payers', 'Insurance/List', 'main');
INSERT INTO `menu` VALUES (26, 'billing', 24, '', 'children', 200, 'Fee Schedules', 'FeeSchedule/List', 'main');
INSERT INTO `menu` VALUES (27, 'billing', 24, '', 'children', 300, 'Discount Tables', 'FeeScheduleDiscount/List', 'main');
INSERT INTO `menu` VALUES (28, 'billing', 24, '', 'children', 400, 'Superbills', 'Superbill/List', 'main');
INSERT INTO `menu` VALUES (29, 'billing', 24, '', 'children', 500, 'Import 835', 'X12Import/List', 'main');
INSERT INTO `menu` VALUES (30, 'admin', 1, '', 'children', 10, 'Calendar', '', 'main');
INSERT INTO `menu` VALUES (31, 'admin', 30, '', 'children', 100, 'Schedules', 'Schedule/list', 'main');
INSERT INTO `menu` VALUES (32, 'admin', 30, '', 'children', 200, 'Templates', 'AppointmentTemplate/list', 'main');
INSERT INTO `menu` VALUES (33, 'admin', 1, '', 'children', 20, 'Patient', '', 'main');
INSERT INTO `menu` VALUES (34, 'admin', 33, '', 'children', 100, 'Labs', 'Labs/List', 'main');
INSERT INTO `menu` VALUES (35, 'admin', 33, '', 'children', 200, 'EMR Plugins', 'Form/List', 'main');
INSERT INTO `menu` VALUES (36, 'admin', 33, '', 'children', 300, 'Document Categories', 'DocumentCategory/List', 'main');
INSERT INTO `menu` VALUES (37, 'admin', 1, '', 'children', 30, 'Biling', '', 'main');
INSERT INTO `menu` VALUES (38, 'admin', 37, '', 'children', 100, 'Payers', 'Insurance/List', 'main');
INSERT INTO `menu` VALUES (39, 'admin', 37, '', 'children', 200, 'Fee Schedules', 'FeeSchedule/List', 'main');
INSERT INTO `menu` VALUES (40, 'admin', 37, '', 'children', 300, 'Discount Tables', 'FeeSchedule/default', 'main');
INSERT INTO `menu` VALUES (41, 'admin', 37, '', 'children', 400, 'Superbills', 'Superbill/List', 'main');
INSERT INTO `menu` VALUES (42, 'admin', 37, '', 'children', 500, 'Input 835', 'X12Import/List', 'main');
INSERT INTO `menu` VALUES (43, 'admin', 1, '', 'children', 40, 'Setup', '', 'main');
INSERT INTO `menu` VALUES (44, 'admin', 43, '', 'children', 100, 'Facilities', 'Location/List', 'main');
INSERT INTO `menu` VALUES (45, 'admin', 43, '', 'children', 200, 'Users', 'User/List', 'main');
INSERT INTO `menu` VALUES (46, 'admin', 43, '', 'children', 300, 'Enumerations', 'Enumeration/List', 'main');
INSERT INTO `menu` VALUES (47, 'admin', 43, '', 'children', 400, 'ACL Editor', 'Admin/Acl', 'main');
INSERT INTO `menu` VALUES (48, 'admin', 43, '', 'children', 500, 'Timed Events', 'Cronnable/List', 'main');
INSERT INTO `menu` VALUES (49, 'admin', 1, '', 'children', 50, 'Reports/Forms', '', 'main');
INSERT INTO `menu` VALUES (50, 'admin', 49, '', 'children', 100, 'Reports', 'Report/List', 'main');
INSERT INTO `menu` VALUES (51, 'admin', 49, '', 'children', 200, 'Forms', 'Form/List', 'main');
INSERT INTO `menu` VALUES (52, 'admin', 49, '', 'children', 300, 'Connect Reports', 'Report/Connect', 'main');
INSERT INTO `menu` VALUES (53, 'admin', 49, '', 'children', 400, 'Connect Forms', 'Form/Connect', 'main');
INSERT INTO `menu` VALUES (54, 'all', 1, '', 'children', 5000, 'Practice', '', 'main');
INSERT INTO `menu` VALUES (55, 'all', 1, '', 'children', 400, 'My Account', '', 'main');
INSERT INTO `menu` VALUES (56, 'all', 55, '', 'children', 100, 'Change Password', 'MyAccount/Password', 'main');
INSERT INTO `menu` VALUES (57, 'patient', 1, '', 'children', -1, 'Encounter Forms', '', 'main/Encounter');
INSERT INTO `menu` VALUES (58, 'patient', 1, '', 'children', -1, 'Dashboard Forms', '', 'main/Patient');
INSERT INTO `menu` VALUES (59, 'patient', 1, '', 'children', -1, 'Dashboard Reports', '', 'main/Patient');
