<?="<?xml version='1.0' encoding='iso-8859-1'?>"?>
<toolbar>
	<item id="new_problem" type="button" img="newproblem.png" imgdis="newproblem.png" height="50" width="80" title="<?=__('New Problem')?>" text="<?=htmlspecialchars('<div style="margin-top:-5px;">'.__('New Problem').'</div>')?>" />
	<item id="edit_problem" type="button" img="editproblem.png" imgdis="editproblem.png" height="50" width="50px" title="<?=__('Edit')?>" enabled="false" text="<?=htmlspecialchars('<div style="margin-top:-5px;">'.__('Edit').'</div>')?>" />
	<item id="remove_problem" type="button" img="removeproblem.png" imgdis="removeproblem.png" height="50" width="50px" title="<?=__('Remove')?>" enabled="false" text="<?=htmlspecialchars('<div style="margin-top:-5px;">'.__('Remove').'</div>')?>" />
	<item id="sep1" type="separator" />
	<item id="annotate_problem" type="button" img="annotateproblem.png" imgdis="annotateproblem.png" height="50" width="70px" title="<?=__('Annotate')?>" enabled="false" text="<?=htmlspecialchars('<div style="margin-top:-5px;">'.__('Annotate').'</div>')?>" />
</toolbar>
