
<div style="width:100%;">
<?if ($this->message) :?>
<div style="background-color:PaleGreen; width:100%;">
<?=$this->message?>
</div>
<?endif;?>

<?=$this->form->renderOpen()?>

<div style="margin-left:10px;">
<?foreach ($this->form->getErrorMessages() as $error) {?>
<?=$error?>
<?}?>
</div>

<div class="formRow" style="padding-top:4px;">
	<?=$this->form->guid->renderLabel()?>
	<?$this->form->guid->setAttrib('size',55)?>
	<?=$this->form->guidInput()?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->name->renderLabel()?>
	<?$this->form->name->setAttrib('size',30)?>
	<?=$this->form->nameInput()?>
	<?=$this->formButton('generateId',__('Generate Code'),array('onClick'=>'generateDefaultDatasource()'))?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->datasourceInput('FormTextarea',array('style'=>'width:470px;height:250px;'))?>
</div>
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->formHidden('id',$this->form->dataIntegrationDatasourceId->getValue())?>
	<?=$this->form->dataIntegrationDatasourceIdInput('FormHidden')?>
	<?=$this->formHidden('type',$this->form->handlerType->getValue())?>
	<?=$this->form->handlerTypeInput('FormHidden')?>
	<?=$this->form->okInput()?>
	<?=$this->formButton('cancelId',__('Cancel'),array('onClick'=>'dhxWins.window(\''.$this->form->getWindow().'\').close()'))?>
</div>

<script>
var defaultDatasource = (<r><![CDATA[<?=$this->datasource->defaultTemplate()?>]]></r>).toString();

function postSubmit<?=$this->form->getId()?>(data) {
<?if (strlen($this->callback) > 0):?>
	if (window.<?=$this->callback?>) {
		window.<?=$this->callback?>(data);
	}
<?endif;?>
	dhxWins.window('<?=$this->form->getWindow()?>').close();
	return false;
}

function preSubmit<?=$this->form->getId()?>() {
	var validName = "class "+globalNormalizedName(dojo.byId("<?=$this->form->name->getId()?>").value)+"DataIntegrationDatasource";
	var datasource = dojo.byId("<?=$this->form->datasource->getId()?>").value;
	if (datasource.substr(0,validName.length) != validName) {
		alert("Must be defined as: \n"+validName);
		return false;
	}
	return true;
}

function generateDefaultDatasource() {
	var name = dojo.byId("<?=$this->form->name->getId()?>").value;
	if (name.length <= 0) {
		alert("<?=__('Name must be supplied.')?>");
		return;
	}
	if (!confirm("Continue?")) return;
	dojo.byId("<?=$this->form->datasource->getId()?>").value = defaultDatasource.replace("class [[ClassName]]DataIntegrationDatasource","class "+globalNormalizedName(name)+"DataIntegrationDatasource");
}
</script>

<?=$this->form->renderClose()?>
</div>

