<div style="float:left;">
	<?=$this->form->renderOpen()?>
	<div class="formRow" style="padding-top:4px;">
		<?=$this->form->paymentDate->renderLabel()?>
		<?=$this->form->paymentDateInput('FormDateText')?>
	</div>
	<br style="clear:left;" />
	<div class="formRow" style="padding-top:4px;">
		<?=$this->form->amount->renderLabel()?>
		<?=$this->form->amountInput()?>
	</div>
	<br style="clear:left;" />
	<div class="formRow" style="padding-top:4px;">
		<?=$this->form->paymentType->renderLabel()?>
		<?=$this->form->paymentTypeInput('FormSelect',array(
			'options'=>$this->paymentTypes,
		))?>
	</div>
	<br style="clear:left;" />
	<div class="formRow" style="padding-top:4px;">
		<?=$this->form->title->renderLabel()?>
		<?=$this->form->titleInput()?>
	</div>
	<br style="clear:left;" />
	<br style="clear:left;" />
	<div class="formRow" style="padding-top:4px;">
		<?=$this->form->encounterIdInput('FormHidden')?>
		<?=$this->form->personIdInput('FormHidden')?>
		<?=$this->form->appointmentIdInput('FormHidden')?>
		<?=$this->form->okInput()?>
	</div>
	<?=$this->form->renderClose()?>
</div>
<script>
function postSubmit<?=$this->form->getId()?>(data) {
	dhxWins.window("<?=$this->form->getWindow()?>").close();
	if (<?=$this->columnId?> > -1) {
		calendarLoadEvents(["<?=$this->columnId?>"]);
	}
	return false;
}
</script>
