<?=$this->form->renderOpen()?>

<div class="formRow" style="padding-top:4px;">
	<?=$this->form->resource->renderLabel()?>
	<?=$this->form->resourceInput('FormText',array('style'=>'width:300px;'))?>
</div>
<br style="clear:left;" />
<br style="clear:left;" />
<div class="formRow" style="padding-top:4px;">
	<?=$this->form->okInput()?>
	<?=$this->form->educationResourceIdInput('FormHidden')?>
</div>

<?=$this->form->renderClose()?>

<script>
function postSubmit<?=$this->form->getId()?>(data) {
	dhxWins.window("<?=$this->form->getWindow()?>").close();
	return false;
}
</script>
