<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="sep0" type="separator"/>
	<item id="clearWeek" type="button" img="clear.png" height="45"><![CDATA[<div style="margin-top:-5px;"><?=__('Clear Week')?></div>]]></item>
	<item id="saveTemplate" type="button" img="save.png" height="45"><![CDATA[<div style="margin-top:-5px;"><?=__('Save Template')?></div>]]></item>
	<item id="loadTemplate" type="button" img="getStatus.png" height="45"><![CDATA[<div style="margin-top:-5px;"><?=__('Load Template')?></div>]]></item>
	<item id="repeatTemplate" type="button" img="newproblem.png" height="45"><![CDATA[<div style="margin-top:-5px;"><?=__('Duplicate Schedule')?></div>]]></item>
	<item id="copy2User" type="button" img="copydocument.png" height="45"><![CDATA[<div style="margin-top:-5px;"><?=__('Copy to User')?></div>]]></item>
</toolbar>
