<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="tbNewMacro" type="button" title="New Macro" img="newproblem.png" imgdis="newproblem.png">
		<![CDATA[<div style="margin-top:-5px;">New</div> ]]>
	</item>
	<item id="tbEditMacro" type="button" title="Edit Macro" img="editproblem.png" imgdis="editproblem.png">
		<![CDATA[<div style="margin-top:-5px;">Edit</div> ]]>
	</item>
	<item id="tbDeleteMacro" type="button" title="Delete Macro" img="removeproblem.png"  imgdis="removeproblem.png">
		<![CDATA[<div style="margin-top:-5px;">Delete</div>]]>
	</item>
</toolbar>
