<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="newId" type="button" title="New Fee Schedule" img="newproblem.png" imgdis="newproblem.png">
		<![CDATA[<div style="margin-top:-5px;">New</div> ]]>
	</item>
	<item id="editId" type="button" title="Edit Fee Schedule" img="editproblem.png" imgdis="editproblem.png">
		<![CDATA[<div style="margin-top:-5px;">Edit</div> ]]>
	</item>
	<item id="deleteId" type="button" title="Delete Fee Schedule" img="removeproblem.png"  imgdis="removeproblem.png">
		<![CDATA[<div style="margin-top:-5px;">Delete</div>]]>
	</item>
	<item id="setFeesId" type="button" title="Set Fees" img="editproblem.png"  imgdis="editproblem.png">
		<![CDATA[<div style="margin-top:-5px;">Set Fees</div>]]>
	</item>
	<item id="refreshId" type="button" title="Refresh Fee Schedule List" img="refresh.png"  imgdis="refresh.png">
		<![CDATA[<div style="margin-top:-5px;">Refresh</div>]]>
	</item>
</toolbar>
