<?='<?xml version="1.0" encoding="iso-8859-1"?>'?>
<toolbar>
	<item id="newVitals" type="button" img="newproblem.png" height="45"><![CDATA[ <div style="margin-top:-5px;"><?=__('New Vitals')?></div> ]]></item>
	<item id="sep1" type="separator" />
	<item id="sep2" type="separator" />
	<item id="sep3" type="separator" />
	<item id="sep4" type="separator" />
	<item id="sep5" type="separator" />
	<item id="sep6" type="separator" />
	<item id="sep7" type="separator" />
	<item id="sep8" type="separator" />
	<item id="sep9" type="separator" />
	<item id="sep10" type="separator" />
	<item id="print" type="button" img="print.png" height="45"><![CDATA[ <div style="margin-top:-5px;"><?=__('Print')?></div> ]]></item>
	<item id="pediatricGrowth" type="button" img="growthChart.png" height="45"><![CDATA[ <div style="margin-top:-5px;"><?=__('Pediatric Growth Charts')?></div> ]]></item>
</toolbar>
